apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demoms
  name: demoms
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: demoms
status:
  loadBalancer: {}
